# Generated by Django 5.2.4 on 2025-07-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='personal_profile_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='personal_profile_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
