# Generated by Django 5.2.4 on 2025-07-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_companyinfo_personal_profile_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='Homepage_middle_details_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='Homepage_middle_title_text',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_photo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_text',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='learn_more_button',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_photo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_small_display_text',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_title_text',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='rating_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='trusted_people_photo',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='trusted_people_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='watch_video',
            field=models.URLField(blank=True),
        ),
    ]
