# Generated by Django 5.2.4 on 2025-07-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_companyinfo_homepage_middle_details_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='circle_photo',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='circle_text',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='lower_buttons_photo',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='lower_buttons_small_display_text',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='lower_buttons_title_text',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='trusted_people_photo',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_photo_eighth',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_photo_fifth',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_photo_first',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_photo_fourth',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_photo_nineth',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_photo_second',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_photo_seventh',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_photo_six',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_photo_tenth',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_photo_third',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_text_eighth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_text_fifth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_text_first',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_text_fourth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_text_nineth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_text_second',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_text_seventh',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_text_six',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_text_tenth',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='circle_text_third',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_photo_first',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_photo_second',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_photo_third',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_small_display_text_first',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_small_display_text_second',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_small_display_text_third',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_title_text_first',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_title_text_second',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='lower_buttons_title_text_third',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='trusted_people_photo_fifth',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='trusted_people_photo_first',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='trusted_people_photo_fourth',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='trusted_people_photo_second',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='trusted_people_photo_third',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
