# Generated by Django 5.2.4 on 2025-07-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_companyinfo_circle_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='use_video_as_main_button',
            field=models.BooleanField(default=False, verbose_name='Use this video as the main button?'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='watch_video',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Video URL or Embed Code'),
        ),
    ]
